### ISSUE TITLE
Data fetching repeated on theme change

### ISSUE THREAD

**Issue by Tanmay000009** [Team-Fourth-Dimension/FFCSeZ#8]
When server data is updated, app fetches new data from server. But if I change the theme, it'll refetch data. Same will going on if I keep on changing theme. This stops once the app is restarted.

**Comment by 1407arjun** [comment]
I couldn't see this happening or replicate the issue on my test devices. If the issue persists or if you can provide us with the steps that led to this issue, reopen this issue so that we can replicate the same in our tests too in order to identify the bug. Thank you!
